site_name: Assignment 2 - Group 2
nav:
    - Home: index.md
    - Plan: 'Test Plan.md'
    - Sheet One: 'Test Case Sheet 1.md'
    - Sheet Two: 'Test Case Sheet 2.md'
    - Sheet Three: 'Test Case Sheet 3.md'
    - Report One: 'Test Case Report 1.md'
    - Report Two: 'Test Case Report 2.md'
    - Report Three: 'Test Case Report 3.md'
